baseURL = "/"
languageCode = "en-us"
title = "Coder Forge"
theme = "minimal"
disqusShortname = "" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Coder Forge Team"
    description = "Coder Forge enables working adults to learn programming."
    githubUsername = "#"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Articles"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "https://www.meetup.com/Dublin-Coder-Forge/"
    name = "meetup"
    weight = 1

[[menu.icon]]
    url = "https://coderforgeworkspace.slack.com/"
    name = "slack"
    weight = 3


[[menu.icon]]
    url = "https://github.com/xackery/cf"
    name = "github"
    weight = 2